export const gmtStrings = [
  { value: "-12GMT", label: "-12 GMT" },
  { value: "-11GMT", label: "-11 GMT" },
  { value: "-10GMT", label: "-10 GMT" },
  { value: "-9GMT", label: "-9 GMT" },
  { value: "-8GMT", label: "-8 GMT" },
  { value: "-7GMT", label: "-7 GMT" },
  { value: "-6GMT", label: "-6 GMT" },
  { value: "-5GMT", label: "-5 GMT" },
  { value: "-4GMT", label: "-4 GMT" },
  { value: "-3GMT", label: "-3 GMT" },
  { value: "-2GMT", label: "-2 GMT" },
  { value: "-1GMT", label: "-1 GMT" },
  { value: "+0GMT", label: "+0 GMT" },
  { value: "+1GMT", label: "+1 GMT" },
  { value: "+2GMT", label: "+2 GMT" },
  { value: "+3GMT", label: "+3 GMT" },
  { value: "+4GMT", label: "+4 GMT" },
  { value: "+5GMT", label: "+5 GMT" },
  { value: "+6GMT", label: "+6 GMT" },
  { value: "+7GMT", label: "+7 GMT" },
  { value: "+8GMT", label: "+8 GMT" },
  { value: "+9GMT", label: "+9 GMT" },
  { value: "+10GMT", label: "+10 GMT" },
  { value: "+11GMT", label: "+11 GMT" },
  { value: "+12GMT", label: "+12 GMT" },
];

export const colors = [
  "#2573F6",
  "#8CB7FF",
  "#8F3985",
  "#C2185B",
  "#FF9800",
  "#FFEB3B",
  "#00B87C",
  "#D0E888",
  "#454545",
  "#999999",
];
