# Generated by Django 3.2.4 on 2021-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time_zone', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=100000)),
                ('event_tag', models.CharField(max_length=100)),
                ('event_color', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('visibility', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('custom_occurence', models.CharField(max_length=1000)),
                ('repeat_every', models.IntegerField()),
                ('repeat_on', models.CharField(max_length=10)),
                ('ends', models.CharField(max_length=50)),
                ('never', models.CharField(max_length=500)),
                ('on_occurence', models.DateField()),
                ('after_occurence', models.CharField(max_length=500)),
            ],
        ),
    ]
