# Generated by Django 3.2.4 on 2021-09-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
    ]
