# Generated by Django 3.2.4 on 2021-09-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20210831_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_zone',
            field=models.CharField(max_length=250),
        ),
    ]
