# Generated by Django 3.2 on 2021-09-02 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20210902_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='after_occurence',
            new_name='after_occurrence',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='custom_occurence',
            new_name='custom_occurrence',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='event',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='on_occurence',
        ),
        migrations.AddField(
            model_name='reminder',
            name='on_occurrence',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
