# Generated by Django 3.2.4 on 2021-09-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_alter_event_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='event_name',
        ),
    ]
