# Generated by Django 3.2.4 on 2021-09-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_rename_title_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='after_occurence',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='custom_occurence',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='ends',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='event_description',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='event_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='never',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='on_occurence',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_id',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_every',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_on',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
