# Generated by Django 3.2.4 on 2021-09-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_rename_title_event_event_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-event_name', 'availability'), 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
