# Generated by Django 3.2.4 on 2021-09-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_auto_20210901_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_id',
        ),
    ]
