name: Calendar Deployment

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [develop]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pull Repo on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/zc_cal/zc_plugin_company_holiday_calendar
            git stash
            git pull origin develop
            cd ~/zc_cal/zc_plugin_company_holiday_calendar/calendar_frontend
            yarn install
            yarn build
            cd ~/zc_cal/zc_plugin_company_holiday_calendar/calendar_backend
            source venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py collectstatic --noinput
            pkill -u ${{secrets.USERNAME}} gunicorn 
            gunicorn --bind 0.0.0.0:8000 calendar_backend.wsgi --daemon
